### ISSUE TITLE
128 symbols cap

### ISSUE THREAD

**Issue by ntkille** [hexadecimalrs/PoGo-Convenience#11]
It seems that (currently) IOS 12 has a cap of 128 characters. Anything more will not work, i.e. will not return text replacement.

Workaround that worked for me is to:
1. remove hp entries (keep only cp) - yes, more pokemons to check the IV for
2. break the string into 2 separate where each is 129 characters or less - yes, you will need to run 2 searches per pokemon type

Example for larvitar:
string 1: 246&cp14,cp46,cp77,cp108,cp140,cp171,cp203,cp234,cp265,cp297,cp327,cp356,cp386,cp416,cp445,cp475,cp505,cp535,cp564,cp594

string 2:
246&cp624,cp653,cp683,cp713,cp743,cp772,cp802,cp832,cp862,cp891,cp906,cp921,cp936,cp951,cp966

When Apple will (if they will) enable more or unlimited characters for the string is unknown to me.

**Comment by BartmanEH** [comment]
This bug has been fixed in iOS 12.1.1 (now released)
