### ISSUE TITLE
One “list”

### ISSUE THREAD

**Issue by BartmanEH** [hexadecimalrs/PoGo-Convenience#2]
Can you reorganize or add a single list with all in one nicely searchable repository? I think it’s silly to figure out which generation a mon is and have them separated. One list would facilitate a quick search to find any mon.

**Comment by hexadecimalrs** [comment]
Late reply, but the point of having them separated by generation was to make it more "nicely searchable." I don't want each to be cluttered in one folder. This'll make it easy to navigate for future generations as well.

**Comment by BartmanEH** [comment]
Agree to disagree. Consider a quick workflow to access the data: click one
list with all the mons, type in the address bar part of a mon's name, boom!
the mobile browser shows you the results on the page and you click it to
get right to the mon of interest. In the current workflow, you have to
first figure out what generation a mon is, then click that list and still
have to search for the mon because the list is too huge to scroll.

Anyway, I've given my feedback. I can deal with a few extra clicks and
trying to remember what gen a particular mon is.

Thanks,
Bart
